import "@projekt906/ui/globals.css";
import { Toaster } from "@projekt906/ui/components/ui/sonner"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import JotaiProvider from "./_providers/Jotai";
import Header from "./_components/Header";
import { cn } from "@projekt906/ui/lib/utils";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <title>AgniX</title>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#ffc40d" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <JotaiProvider>
        <body className={cn(inter.className,
          `max-w-md mx-auto min-h-screen flex flex-col px-4`)}>
          <Header />
          {children}
          <Footer />
          <Toaster />
        </body>
      </JotaiProvider>
    </html>
  );
}
