import "@projekt906/ui/globals.css";
import { Toaster } from "@projekt906/ui/components/ui/sonner"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import JotaiProvider from "./_providers/Jotai";
import Header from "./_components/Header";
import { cn } from "@projekt906/ui/lib/utils";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <JotaiProvider>
        <body className={cn(inter.className,
          `max-w-md mx-auto min-h-screen flex flex-col`)}>
          <Header />
          {children}
          <Footer />
          <Toaster />
        </body>
      </JotaiProvider>
    </html>
  );
}
